/**
 * Refresh the vendored Nylas docs in docs/reference/.
 *
 *   npm run docs:fetch
 *
 * Every page on developer.nylas.com serves clean markdown when you append .md,
 * so this pulls them down verbatim. The point of vendoring is that an agent
 * working in this repo can grep the docs instead of making network calls.
 *
 * Add a URL to PAGES and re-run to include a new page.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const OUT_DIR = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    "..",
    "docs",
    "reference"
);

const BASE = "https://developer.nylas.com";

/** [local filename, doc path]. Keep grouped and alphabetical-ish within a group. */
const PAGES = [
    // Orientation
    ["coding-agents.md", "/docs/v3/getting-started/coding-agents.md"],
    ["getting-started-email.md", "/docs/v3/getting-started/email.md"],
    ["nylas-connect.md", "/docs/v3/getting-started/nylas-connect.md"],

    // Auth
    ["auth.md", "/docs/v3/auth.md"],
    ["auth-hosted-oauth-apikey.md", "/docs/v3/auth/hosted-oauth-apikey.md"],

    // Email guides
    ["email.md", "/docs/v3/email.md"],
    ["email-messages.md", "/docs/v3/email/messages.md"],
    ["email-send-email.md", "/docs/v3/email/send-email.md"],
    ["email-signatures.md", "/docs/v3/email/signatures.md"],
    ["email-idempotent-send.md", "/docs/v3/email/idempotent-send.md"],
    ["email-parse-messages.md", "/docs/v3/email/parse-messages.md"],
    ["email-threads.md", "/docs/v3/email/threads.md"],
    ["email-attachments.md", "/docs/v3/email/attachments.md"],

    // Webhooks
    ["notifications.md", "/docs/v3/notifications.md"],

    // API reference
    ["api-messages.md", "/docs/reference/api/messages.md"],
    ["api-messages-get-messages.md", "/docs/reference/api/messages/get-messages.md"],
    ["api-messages-get-message.md", "/docs/reference/api/messages/get-messages-id.md"],
    ["api-messages-clean.md", "/docs/reference/api/messages/clean-messages.md"],
    ["api-messages-send.md", "/docs/reference/api/messages/send-message.md"],
    ["api-signatures.md", "/docs/reference/api/signatures.md"],
];

const HEADER = (url) =>
    `<!--\n` +
    `  Vendored from ${url}\n` +
    `  Do not edit by hand — run \`npm run docs:fetch\` to refresh.\n` +
    `-->\n\n`;

const fetchPage = async (docPath, attempt = 1) => {
    const url = `${BASE}${docPath}`;

    try {
        const res = await fetch(url, { headers: { Accept: "text/markdown" } });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return { url, markdown: await res.text() };
    } catch (err) {
        // The docs site rate-limits bursts; one backoff clears it in practice.
        if (attempt < 3) {
            await new Promise((resolve) => setTimeout(resolve, attempt * 1500));
            return fetchPage(docPath, attempt + 1);
        }
        throw new Error(`${url} -> ${err.message}`);
    }
};

fs.mkdirSync(OUT_DIR, { recursive: true });

const failures = [];
const written = [];

for (const [filename, docPath] of PAGES) {
    process.stdout.write(`  ${filename.padEnd(34)}`);

    try {
        const { url, markdown } = await fetchPage(docPath);
        fs.writeFileSync(path.join(OUT_DIR, filename), HEADER(url) + markdown);

        const kb = (Buffer.byteLength(markdown) / 1024).toFixed(1);
        console.log(`ok  ${kb.padStart(6)} KB`);
        written.push({ filename, url, kb });
    } catch (err) {
        console.log(`FAILED  ${err.message}`);
        failures.push(filename);
    }
}

// An index so an agent can see what's vendored without listing the directory.
const manifest =
    `# Vendored Nylas documentation\n\n` +
    `Generated by \`npm run docs:fetch\` on ${new Date().toISOString().slice(0, 10)}.\n` +
    `These are verbatim copies of the official docs. Do not edit them by hand.\n\n` +
    `| File | Source |\n| --- | --- |\n` +
    written.map((p) => `| \`${p.filename}\` | ${p.url} |`).join("\n") +
    `\n`;

fs.writeFileSync(path.join(OUT_DIR, "_MANIFEST.md"), manifest);

console.log(`\n  ${written.length} page(s) written to docs/reference/`);
if (failures.length) {
    console.log(`  ${failures.length} failed: ${failures.join(", ")}`);
    process.exitCode = 1;
}
